export const SET_USER = 'SET_USER';
export const LOAD_USER_ITEMS = 'LOAD_USER_ITEMS';
export const LOAD_USER_DETAILS = 'LOAD_USER_DETAILS';
export const LOAD_PRODUCT_TYPES = 'LOAD_PRODUCT_TYPES';
export const LOAD_PRODUCT_TYPE_TAGS = 'LOAD_PRODUCT_TYPE_TAGS';
export const LOAD_PRODUCT_DEFS = 'LOAD_PRODUCT_TYPES';

export const GET_ORDERS = 'GET_ORDERS';